### PR TITLE
Delete book test

### PR DESCRIPTION
**Pull request by mvn-minhphan-dn**
## Description
Test for delete book and its relationship.
## Reference Requirements
- Product Backlog ID: PBI-8
- Task ID: TI-4

## Reference Isuees
None

## Migrations
NO

## Impacted Areas in Application
None

## SQL query and `explain`
None

### CODE REVIEW

**Review by at-phutran2 — COMMENTED** [review]
checkout nhánh khác để fix blade view Minh hì, fix lại convention

**Comment by at-phutran2** [comment]
LGTM

**Review by ghost — CHANGES_REQUESTED** [review]
- test case chưa rõ ràng. chưa có testcase fail, testcase với trường hợp không login.
- refactor code cho gọn.

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
