### PR TITLE
Api document for delete post

### PR DESCRIPTION
**Pull request by mvn-tamnguyen4-dn**
## Description
Api document for delete post
## Reference Requirements
- Product Backlog ID: PBI-1
- Task ID: TI-1

## Reference Isuees
None

## Migrations
NO

## Impacted Areas in Application
- docs/api-references/posts.md

## SQL query and `explain`
None

### CODE REVIEW

**Review by at-phutran2 — COMMENTED** [review]
LGTM

**Review by ghost — COMMENTED** [review]
please check my comment

**Review by phanngoctuan1990 — APPROVED** [review]
GLTM

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
